// valuesData.js
export const valuesData = {

  Results: [
    "Accomplishment",
    "Achievement",
    "Completion",
    "Contribution",
    "Effectiveness",
    "Impact",
    "Performance",
    "Productivity",
    "Profitability",
    "Prosperity",
    "Punctuality",
    "Results",
    "Success",
    "Timeliness",
    "Value Creation",
    "Wealth"
  ],

  Competition: [
    "Aggressiveness",
    "Ambition",
    "Assertiveness",
    "Boldness",
    "Competition",
    "Decisiveness",
    "Directness",
    "Dominance",
    "Fierce",
    "Intensity",
    "Power",
    "Victory",
    "Winning"
  ],

  Teamwork: [
    "Appreciation",
    "Citizenship",
    "Collaboration",
    "Community",
    "Connection",
    "Cooperation",
    "Family",
    "Friendship",
    "Harmony",
    "Partnership",
    "Relationships",
    "Sharing",
    "Support",
    "Synergy",
    "Teamwork",
    "Unity"
  ],

  Compassion: [
    "Acceptance",
    "Affection",
    "Altruism",
    "Belonging",
    "Caring",
    "Charity",
    "Comfort",
    "Compassion",
    "Concern for Others",
    "Decency",
    "Empathy",
    "Generosity",
    "Goodwill",
    "Heart",
    "Kindness",
    "Love",
    "Philanthropy",
    "Selfless",
    "Sensitivity",
    "Service",
    "Understanding"
  ],

  Determination: [
    "Conviction",
    "Determination",
    "Endurance",
    "Focus",
    "Fortitude",
    "Hard Work",
    "Perseverance",
    "Resilience",
    "Resolve",
    "Spirit",
    "Strength",
    "Toughness",
    "Willfulness"
  ],

  Commitment: [
    "Accountability",
    "Commitment",
    "Dedication",
    "Dependability",
    "Devotion",
    "Duty",
    "Faith",
    "Fidelity",
    "Honor",
    "Loyalty",
    "Patriotism",
    "Reliability",
    "Responsibility",
    "Sacrifice"
  ],

  Initiative: [
    "Discipline",
    "Drive",
    "Eagerness",
    "Empowering",
    "Energy",
    "Independence",
    "Individuality",
    "Initiative",
    "Optimism",
    "Proactive",
    "Rigor",
    "Self-Motivation",
    "Self-Reliance",
    "Vitality"
  ],

  Creative: [
    "Creativity",
    "Curiosity",
    "Differentiation",
    "Discovery",
    "Dreaming",
    "Fresh Ideas",
    "Genius",
    "Imagination",
    "Inspiration",
    "Invention",
    "Originality",
    "Talent",
    "Uniqueness",
    "Variety",
    "Wonder"
  ],

  Irreverent: [
    "Anti-Bureaucratic",
    "Anti-Corporate",
    "Informal",
    "Irreverence",
    "No Bureaucracy",
    "Profane"
  ],

  Longevity: [
    "Anticipation",
    "Focus on Future",
    "Foresight",
    "Insight",
    "Intuition",
    "Investment",
    "Leadership",
    "Longevity",
    "Mindful",
    "Perception",
    "Self-Awareness",
    "Stewardship",
    "Sustainability",
    "Vision"
  ],

  Adventure: [
    "Adventure",
    "Bravery",
    "Challenge",
    "Courage",
    "Daring",
    "Exploration",
    "Fearless",
    "Heroism",
    "Progress",
    "Pursuit",
    "Risk Taking",
    "Valor"
  ],

  Capable: [
    "Brilliance",
    "Capability",
    "Cleverness",
    "Competence",
    "Craftsmanship",
    "Cunning",
    "Depth",
    "Expertise",
    "Intelligence",
    "Mastery",
    "Maturity",
    "Quality",
    "Skill",
    "Wisdom"
  ],

  Learning: [
    "Continuous Improvement",
    "Development",
    "Education",
    "Engagement",
    "Growth",
    "Knowledge",
    "Learning",
    "Motivation",
    "Personal Growth",
    "Potential",
    "Training"
  ],

  Organization: [
    "Cleanliness",
    "Hygiene",
    "Neatness",
    "Organization",
    "Sanitary"
  ],

  Awareness: [
    "Alertness",
    "Attentiveness",
    "Awareness",
    "Clear-Minded",
    "Confidence",
    "Consciousness",
    "Preparedness",
    "Responsiveness",
    "Watchfulness"
  ],

  Structure: [
    "Conformity",
    "Control",
    "Formal",
    "History",
    "Holiness",
    "Obedience",
    "Order",
    "Preservation",
    "Reverence",
    "Rule of Law",
    "Stability",
    "Structure",
    "Tradition"
  ],

  Change: [
    "Adaptability",
    "Agility",
    "Change",
    "Entrepreneurship",
    "Flexibility",
    "Innovation",
    "Speed"
  ],

  Excellence: [
    "Above and Beyond",
    "Being the Best",
    "Best People",
    "Exceed Expectations",
    "Excellence",
    "Greatness",
    "Perfection",
    "Pride"
  ],

  Safety: [
    "Confidentiality",
    "Discretion",
    "Privacy",
    "Restraint",
    "Safety",
    "Security",
    "Self-Control"
  ],

  Accuracy: [
    "Accuracy",
    "Attention to Detail",
    "Carefulness",
    "Concentration",
    "Consistency",
    "Diligence",
    "Meticulous",
    "Precision",
    "Thorough"
  ],

  CustomerFocus: [
    "Customer Focus",
    "Customer Satisfaction",
    "Customer Service",
    "Delight",
    "Patient-Centered",
    "Patients",
    "Satisfaction"
  ],

  Friendly: [
    "Accessibility",
    "Approachability",
    "Availability",
    "Communication",
    "Friendly",
    "Inviting",
    "Warmth",
    "Welcoming"
  ],

  Integrity: [
    "Candor",
    "Character",
    "Credibility",
    "Ethical",
    "Honesty",
    "Humility",
    "Integrity",
    "Trust",
    "Truth",
    "Virtue"
  ],

  Sincerity: [
    "Cordiality",
    "Courtesy",
    "Encouragement",
    "Hospitality",
    "Listening",
    "Pleasantness",
    "Sincerity"
  ],

  Rational: [
    "Common Sense",
    "Down-to-Earth",
    "Efficiency",
    "Frugality",
    "Logic",
    "Moderation",
    "Modesty",
    "Pragmatic",
    "Prudence",
    "Rationality",
    "Resourcefulness",
    "Temperance",
    "Utility"
  ],

  Spontaneous: [
    "Excitement",
    "Exhilarating",
    "Exuberance",
    "Expressive",
    "Flair",
    "Intuitive",
    "Lively",
    "Outrageous",
    "Passion",
    "Spirituality",
    "Spontaneous",
    "Surprise"
  ],

  Fun: [
    "Amusement",
    "Cheerful",
    "Enjoyment",
    "Entertainment",
    "Enthusiasm",
    "Fitness",
    "Fun",
    "Happiness",
    "Health",
    "Hope",
    "Humor",
    "Joy",
    "Playfulness",
    "Recreation",
    "Silliness",
    "Work/Life Balance"
  ],

  Composure: [
    "Calmness",
    "Composure",
    "Contentment",
    "Meekness",
    "Patience",
    "Peace",
    "Poise",
    "Reflection",
    "Relaxation",
    "Serenity",
    "Silence",
    "Simplicity",
    "Solitude",
    "Tranquility",
    "Unflappable"
  ],

  Freedom: [
    "Democratic",
    "Diversity",
    "Equality",
    "Fairness",
    "Freedom",
    "Impartial",
    "Justice",
    "Liberty",
    "Meritocracy",
    "Open-Minded",
    "Openness",
    "Respect",
    "Tolerance",
    "Transparency"
  ],

  Refined: [
    "Beauty",
    "Dignity",
    "Elegance",
    "Fashion",
    "Polish",
    "Professionalism",
    "Refined"
  ],

  Significance: [
    "Famous",
    "Gratitude",
    "Meaning",
    "Recognition",
    "Significance",
    "Status",
    "Thankfulness"
  ]

};

  Competition: [
    "Aggressive",
    "Aggressiveness",
    "Ambition",
    "Assertive",
    "Assertiveness",
    "Bold",
    "Boldness",
    "Competition",
    "Competitive",
    "Decisive",
    "Decisiveness",
    "Direct",
    "Directness",
    "Dominance",
    "Ferocious",
    "Fierce",
    "Intensity",
    "Potency",
    "Power",
    "Powerful",
    "Victorious",
    "Victory",
    "Winning"
  ],

  Teamwork: [
    "Appreciation",
    "Citizenship",
    "Collaboration",
    "Community",
    "Connection",
    "Cooperation",
    "Coordination",
    "Employees",
    "Environment",
    "Family",
    "Family Atmosphere",
    "Friendship",
    "Harmony",
    "Local",
    "Members",
    "Partnership",
    "People",
    "Relationships",
    "Shared Prosperity",
    "Sharing",
    "Support",
    "Synergy",
    "Teamwork",
    "Unity"
  ],

  Compassion: [
    "Acceptance",
    "Affection",
    "Altruism",
    "Belonging",
    "Caring",
    "Charity",
    "Comfort",
    "Compassion",
    "Concern for Others",
    "Decency",
    "Empathy",
    "Generosity",
    "Giving",
    "Goodness",
    "Goodwill",
    "Heart",
    "Helpful",
    "Kindness",
    "Love",
    "Philanthropy",
    "Selfless",
    "Sensitivity",
    "Service",
    "Sympathy",
    "Understanding"
  ],

  Determination: [
    "Conviction",
    "Determination",
    "Determined",
    "Endurance",
    "Firm",
    "Focus",
    "Fortitude",
    "Hard Work",
    "Perseverance",
    "Persistence",
    "Persuasive",
    "Resilience",
    "Resolute",
    "Resolution",
    "Resolve",
    "Spirit",
    "Strength",
    "Tough",
    "Toughness",
    "Willfulness"
  ],

  Commitment: [
    "Accountability",
    "Commitment",
    "Continuity",
    "Dedication",
    "Dependability",
    "Devotion",
    "Devout",
    "Duty",
    "Faith",
    "Faithfulness",
    "Fidelity",
    "Honor",
    "Loyalty",
    "Patriotism",
    "Reliability",
    "Reliable",
    "Responsibility",
    "Sacrifice"
  ],

  Initiative: [
    "Activity",
    "Discipline",
    "Drive",
    "Eagerness",
    "Empower",
    "Empowering",
    "Energy",
    "Independence",
    "Individuality",
    "Industry",
    "Initiative",
    "Optimism",
    "Positive",
    "Proactive",
    "Proactively",
    "Rigor",
    "Self Motivation",
    "Self Responsibility",
    "Self-Directed",
    "Self-Reliance",
    "Vigor",
    "Vital",
    "Vitality"
  ],

  Creative: [
    "Creation",
    "Creative",
    "Creativity",
    "Curiosity",
    "Different",
    "Differentiation",
    "Discovery",
    "Dreaming",
    "Fresh",
    "Fresh Ideas",
    "Genius",
    "Imagination",
    "Inquisitive",
    "Inspiration",
    "Invention",
    "Mystery",
    "Original",
    "Originality",
    "Talent",
    "Unique",
    "Uniqueness",
    "Variety",
    "Wonder"
  ],

  Irreverent: [
    "Anti-Bureaucratic",
    "Anti-Corporate",
    "Impious",
    "Informal",
    "Irreverence",
    "Irreverent",
    "No Bureaucracy",
    "Profane"
  ],

  Longevity: [
    "Anticipate",
    "Anticipation",
    "Focus on Future",
    "Foresight",
    "Insight",
    "Insightful",
    "Intuition",
    "Investing",
    "Investment",
    "Leadership",
    "Longevity",
    "Mindful",
    "Perception",
    "Perceptive",
    "Self Awareness",
    "Stewardship",
    "Sustainability",
    "Vision"
  ],

  Adventure: [
    "Adventure",
    "Adventurous",
    "Bravery",
    "Challenge",
    "Courage",
    "Daring",
    "Exploration",
    "Explore",
    "Fearless",
    "Heroism",
    "Nerve",
    "Progress",
    "Pursue",
    "Pursuit",
    "Risk",
    "Risk Taking",
    "Valor"
  ],

  Capable: [
    "Brilliance",
    "Brilliant",
    "Capability",
    "Capable",
    "Clever",
    "Competence",
    "Competency",
    "Craftiness",
    "Craftsmanship",
    "Cunning",
    "Depth",
    "Experience",
    "Expertise",
    "Fluency",
    "Intelligence",
    "Mastery",
    "Maturity",
    "Quality",
    "Quality of Work",
    "Shrewd",
    "Skill",
    "Skillfulness",
    "Smart",
    "Wisdom"
  ],

  Learning: [
    "Continuous Improvement",
    "Development",
    "Education",
    "Engagement",
    "Growth",
    "Improvement",
    "Knowledge",
    "Learning",
    "Motivation",
    "Personal Development",
    "Personal Growth",
    "Potential",
    "Training"
  ],

  Organization: [
    "Clean",
    "Cleanliness",
    "Hygiene",
    "Neatness",
    "Organization",
    "Sanitary"
  ],

  Awareness: [
    "Alert",
    "Alertness",
    "Attentive",
    "Attentiveness",
    "Awareness",
    "Clear",
    "Clear-Minded",
    "Confidence",
    "Consciousness",
    "Prepared",
    "Responsiveness",
    "Watchful",
    "Watchfulness"
  ],

  Structure: [
    "Conformity",
    "Control",
    "Formal",
    "History",
    "Holiness",
    "Legal",
    "Obedience",
    "Order",
    "Preservation",
    "Reverence",
    "Rule of Law",
    "Serious",
    "Stability",
    "Standardization",
    "Structure",
    "Systemization",
    "Traditional"
  ],

  Change: [
    "Adaptability",
    "Agility",
    "Change",
    "Entrepreneurship",
    "Fast",
    "Flexibility",
    "Flexible",
    "Innovation",
    "Innovative",
    "Speed"
  ],

  Excellence: [
    "Above and Beyond",
    "Being the Best",
    "Best",
    "Best People",
    "Exceed Expectations",
    "Excellence",
    "Great",
    "Greatness",
    "Perfection",
    "Pride"
  ],

  Safety: [
    "Confidential",
    "Confidentiality",
    "Discretion",
    "Privacy",
    "Restraint",
    "Safety",
    "Security",
    "Self-Control",
    "Stealth"
  ],

  Accuracy: [
    "Accuracy",
    "Accurate",
    "Attention to Detail",
    "Careful",
    "Carefulness",
    "Concentration",
    "Consistency",
    "Diligence",
    "Meticulous",
    "Precise",
    "Precision",
    "Thorough"
  ],

  CustomerFocus: [
    "Clients",
    "Customer Focus",
    "Customer Satisfaction",
    "Customer Service",
    "Customers",
    "Delight",
    "Patient-Centered",
    "Patient-Focused",
    "Patients",
    "Patient-Satisfaction",
    "Satisfaction"
  ],

  Friendly: [
    "Accessibility",
    "Approachability",
    "Approachable",
    "Availability",
    "Available",
    "Communication",
    "Friendly",
    "Inviting",
    "Warmth",
    "Welcoming"
  ],

  Integrity: [
    "Candor",
    "Character",
    "Credibility",
    "Ethical",
    "Honesty",
    "Humble",
    "Humility",
    "Integrity",
    "Purity",
    "Trust",
    "Trustworthy",
    "Truth",
    "Virtue"
  ],

  Sincerity: [
    "Cordiality",
    "Courtesy",
    "Encouragement",
    "Guidance",
    "Hospitality",
    "Listening",
    "Pleasantness",
    "Sincerity"
  ],

  Rational: [
    "Certainty",
    "Common Sense",
    "Correct",
    "Down-to-Earth",
    "Economy",
    "Efficiency",
    "Efficient",
    "Frugality",
    "Level-Headed",
    "Logic",
    "Moderation",
    "Modesty",
    "Practical",
    "Pragmatic",
    "Prudence",
    "Rational",
    "Real",
    "Realistic",
    "Reason",
    "Resourceful",
    "Resourcefulness",
    "Temperance",
    "Useful",
    "Utility"
  ],

  Spontaneous: [
    "Ease of Use",
    "Excitement",
    "Exciting",
    "Exhilarating",
    "Exuberance",
    "Expressive",
    "Extrovert",
    "Flair",
    "Intuitive",
    "Lively",
    "Outrageous",
    "Passion",
    "Spirituality",
    "Spontaneous",
    "Surprise"
  ],

  Fun: [
    "Amusement",
    "Cheerful",
    "Enjoyment",
    "Entertainment",
    "Enthusiasm",
    "Fitness",
    "Fun",
    "Happiness",
    "Health",
    "Hope",
    "Hopeful",
    "Humor",
    "Joy",
    "Play",
    "Playfulness",
    "Recreation",
    "Sense of Humor",
    "Silliness",
    "Work/Life Balance"
  ],

  Composure: [
    "Calm",
    "Calmness",
    "Composure",
    "Content",
    "Contentment",
    "Meekness",
    "Mellow",
    "Patience",
    "Peace",
    "Poise",
    "Reflection",
    "Relaxation",
    "Rest",
    "Serenity",
    "Silence",
    "Simplicity",
    "Solitude",
    "Thoughtful",
    "Tranquility",
    "Unflappable"
  ],

  Freedom: [
    "Democratic",
    "Diversity",
    "Equality",
    "Equitable",
    "Fairness",
    "Freedom",
    "Impartial",
    "Justice",
    "Liberty",
    "Merit",
    "Meritocracy",
    "Open",
    "Open-Minded",
    "Openness",
    "Respect",
    "Respect for Others",
    "Respect for the Individual",
    "Tolerance",
    "Transparency"
  ],

  Refined: [
    "Beauty",
    "Dignity",
    "Elegance",
    "Fashion",
    "Polish",
    "Professionalism",
    "Refined"
  ],

  Significance: [
    "Famous",
    "Gratitude",
    "Meaning",
    "Popularity",
    "Recognition",
    "Significance",
    "Status",
    "Thankful"
  ]

};
